name: Testing "DShotRMT Library" (official)

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  checking_lib:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32
          libraries: DShotRMT
          sketch-paths: examples/dshot300/dshot300.ino
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
        
      - uses: actions/upload-artifact@v4
        with:
          name: sketches-report-esp32
          path: ${{ env.SKETCHES_REPORTS_PATH }}
