name: Arduino Lint Check Library

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI 
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install Arduino Lint 
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | BINDIR=/usr/local/bin sh
          
      - name: Install DShotRMT as Library
        run: |
          mkdir -p $HOME/Arduino/libraries
          ln -s $PWD $HOME/Arduino/libraries/DShotRMT

      - name: Arduino Lint Check
        run: |
          arduino-lint $PWD --recursive --library-manager update --verbose

      - name: Compile dshot300.ino example sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 examples/dshot300/dshot300.ino --verbose
          